In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

In [2]:
df1 = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104],
    'Name': ['Rahul', 'Priya', 'Aman', 'Sneha'],
    'Department': ['CSE', 'CSE', 'ECE', 'ECE'],
    'Marks': [85, 92, 78, 88]
})

print("DataFrame 1:")
display(df1)

DataFrame 1:

   Student_ID   Name Department  Marks
0         101  Rahul        CSE     85
1         102  Priya        CSE     92
2         103   Aman        ECE     78
3         104  Sneha        ECE     88

In [3]:
df2 = pd.DataFrame({
    'Student_ID': [105, 106, 107, 108],
    'Name': ['Arjun', 'Neha', 'Rohan', 'Anjali'],
    'Department': ['CSE', 'ECE', 'CSE', 'ECE'],
    'Marks': [90, 76, 95, 82]
})

print("DataFrame 2:")
display(df2)

DataFrame 2:

   Student_ID    Name Department  Marks
0         105   Arjun        CSE     90
1         106    Neha        ECE     76
2         107   Rohan        CSE     95
3         108  Anjali        ECE     82

In [4]:
# Create hierarchical index
multi_df = df1.set_index(['Department', 'Student_ID'])

print("DataFrame with Hierarchical Index:")
display(multi_df)

DataFrame with Hierarchical Index:

                        Name  Marks
Department Student_ID
CSE        101         Rahul     85
           102         Priya     92
ECE        103          Aman     78
           104         Sneha     88

In [5]:
print("CSE Students:")
display(multi_df.loc['CSE'])

CSE Students:

             Name  Marks
Student_ID
101         Rahul     85
102         Priya     92

In [6]:
print("Student ID 102:")
display(multi_df.loc[('CSE', 102)])

Student ID 102:

Name     Priya
Marks       92
Name: (CSE, 102), dtype: object

In [7]:
combined_df = pd.concat(
    [df1, df2],
    ignore_index=True
)

print("Combined DataFrame:")
display(combined_df)

Combined DataFrame:

   Student_ID    Name Department  Marks
0         101   Rahul        CSE     85
1         102   Priya        CSE     92
2         103    Aman        ECE     78
3         104   Sneha        ECE     88
4         105   Arjun        CSE     90
5         106    Neha        ECE     76
6         107   Rohan        CSE     95
7         108  Anjali        ECE     82

In [8]:
marks1 = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104],
    'Internal': [20, 22, 18, 21]
})

marks2 = pd.DataFrame({
    'External': [65, 70, 60, 67]
})

combined_columns = pd.concat(
    [marks1, marks2],
    axis=1
)

print("Column-wise Combined DataFrame:")
display(combined_columns)

Column-wise Combined DataFrame:

   Student_ID  Internal  External
0         101        20        65
1         102        22        70
2         103        18        60
3         104        21        67

In [9]:
student_details = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104],
    'Name': ['Rahul', 'Priya', 'Aman', 'Sneha'],
    'Department': ['CSE', 'CSE', 'ECE', 'ECE']
})

student_marks = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104],
    'Marks': [85, 92, 78, 88],
    'Grade': ['A', 'A+', 'B', 'A']
})

merged_df = pd.merge(
    student_details,
    student_marks,
    on='Student_ID',
    how='inner'
)

print("Merged DataFrame:")
display(merged_df)

Merged DataFrame:

   Student_ID   Name Department  Marks Grade
0         101  Rahul        CSE     85     A
1         102  Priya        CSE     92    A+
2         103   Aman        ECE     78     B
3         104  Sneha        ECE     88     A

In [10]:
left_merge = pd.merge(
    student_details,
    student_marks,
    on='Student_ID',
    how='left'
)

display(left_merge)

   Student_ID   Name Department  Marks Grade
0         101  Rahul        CSE     85     A
1         102  Priya        CSE     92    A+
2         103   Aman        ECE     78     B
3         104  Sneha        ECE     88     A

In [11]:
outer_merge = pd.merge(
    student_details,
    student_marks,
    on='Student_ID',
    how='outer'
)

display(outer_merge)

   Student_ID   Name Department  Marks Grade
0         101  Rahul        CSE     85     A
1         102  Priya        CSE     92    A+
2         103   Aman        ECE     78     B
3         104  Sneha        ECE     88     A

In [12]:
marks_df = pd.DataFrame({
    'Student': ['Rahul', 'Priya', 'Aman', 'Sneha'],
    'Maths': [85, 92, 78, 88],
    'Python': [90, 95, 80, 86],
    'DBMS': [82, 89, 75, 91]
})

print("Original DataFrame:")
display(marks_df)

long_df = pd.melt(
    marks_df,
    id_vars=['Student'],
    var_name='Subject',
    value_name='Marks'
)

print("Reshaped DataFrame:")
display(long_df)

Original DataFrame:

  Student  Maths  Python  DBMS
0   Rahul     85      90    82
1   Priya     92      95    89
2    Aman     78      80    75
3   Sneha     88      86    91

Reshaped DataFrame:

   Student Subject  Marks
0    Rahul   Maths     85
1    Priya   Maths     92
2     Aman   Maths     78
3    Sneha   Maths     88
4    Rahul  Python     90
5    Priya  Python     95
6     Aman  Python     80
7    Sneha  Python     86
8    Rahul    DBMS     82
9    Priya    DBMS     89
10    Aman    DBMS     75
11   Sneha    DBMS     91

In [13]:
pivot_df = long_df.pivot(
    index='Student',
    columns='Subject',
    values='Marks'
)

print("Pivoted DataFrame:")
display(pivot_df)

Pivoted DataFrame:

Subject  DBMS  Maths  Python
Student
Aman       75     78      80
Priya      89     92      95
Rahul      82     85      90
Sneha      91     88      86

In [14]:
sales_df = pd.DataFrame({
    'Department': [
        'CSE', 'CSE', 'CSE',
        'ECE', 'ECE', 'ECE'
    ],
    'Semester': [
        1, 1, 2,
        1, 1, 2
    ],
    'Students': [
        60, 65, 70,
        55, 58, 62
    ]
})

print("Sales/Student Data:")
display(sales_df)

pivot_table = pd.pivot_table(
    sales_df,
    values='Students',
    index='Department',
    columns='Semester',
    aggfunc='mean'
)

print("Pivot Table:")
display(pivot_table)

Sales/Student Data:

  Department  Semester  Students
0        CSE         1        60
1        CSE         1        65
2        CSE         2        70
3        ECE         1        55
4        ECE         1        58
5        ECE         2        62

Pivot Table:

Semester       1     2
Department
CSE         62.5  70.0
ECE         56.5  62.0

In [15]:
stacked = pivot_df.stack()

print("Stacked DataFrame:")
display(stacked)

Stacked DataFrame:

Student  Subject
Aman     DBMS       75
         Maths      78
         Python     80
Priya    DBMS       89
         Maths      92
         Python     95
Rahul    DBMS       82
         Maths      85
         Python     90
Sneha    DBMS       91
         Maths      88
         Python     86
dtype: int64

In [16]:
unstacked = stacked.unstack()

print("Unstacked DataFrame:")
display(unstacked)

Unstacked DataFrame:

Subject  DBMS  Maths  Python
Student
Aman       75     78      80
Priya      89     92      95
Rahul      82     85      90
Sneha      91     88      86

In [17]:
print("""
DATA WRANGLING METHODS USED
===========================

1. DataFrame Creation
2. Hierarchical Indexing
3. Combining using concat()
4. Merging using merge()
5. Reshaping using melt()
6. Pivoting using pivot()
7. Pivot Table using pivot_table()
8. Stacking using stack()
9. Unstacking using unstack()
""")

DATA WRANGLING METHODS USED
===========================

1. DataFrame Creation
2. Hierarchical Indexing
3. Combining using concat()
4. Merging using merge()
5. Reshaping using melt()
6. Pivoting using pivot()
7. Pivot Table using pivot_table()
8. Stacking using stack()
9. Unstacking using unstack()